//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long loanId { get; set; }
        public long installmentNo { get; set; }
        public System.DateTime dueDate { get; set; }
        public string remarks { get; set; }
        public decimal installmentAmount { get; set; }
        public string status { get; set; }
    
        public virtual Loan Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
