//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.Installments = new HashSet<Installment>();
        }
    
        public long loanId { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public Nullable<decimal> requestAmount { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public Nullable<System.DateTime> loanStartDate { get; set; }
        public decimal loanAmount { get; set; }
        public long empId { get; set; }
        public int noOfInsatllments { get; set; }
        public string loanStatus { get; set; }
        public string remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installments { get; set; }
    }
}
