//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELReport
    {
        public long empId { get; set; }
        public decimal loanAmount { get; set; }
        public long loanId { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string loanStatus { get; set; }
        public string Email { get; set; }
        public string Cnic { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> DepId { get; set; }
    }
}
